"""add bounded guest sessions

Revision ID: 54e8dd1ca624
Revises: f9ff23b7b84d
Create Date: 2026-10-04 08:45:39.414251
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e8dd1ca624'
down_revision: str | Sequence[str] | None = 'f9ff23b7b84d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('membership_id', sa.String(length=32), nullable=False),
    sa.Column('trip_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['trip_membership.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_guest_session_trip_id', 'guest_session', ['trip_id'], unique=False)
    op.create_index('one_active_guest_session_per_membership', 'guest_session', ['membership_id'], unique=True, postgresql_where='revoked_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_active_guest_session_per_membership', table_name='guest_session', postgresql_where='revoked_at IS NULL')
    op.drop_index('ix_guest_session_trip_id', table_name='guest_session')
    op.drop_table('guest_session')
    # ### end Alembic commands ###
