"""baseline existing schema

Revision ID: f9ff23b7b84d
Revises:
Create Date: 2026-10-03 23:45:54.977333
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ff23b7b84d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('english_name', sa.String(length=300), nullable=True),
    sa.Column('local_name', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('opening_hours', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_place_id', name='uq_place_provider_id')
    )
    op.create_index('ix_place_city_country', 'place', ['city', 'country'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('trip',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('preferred_start_date', sa.Date(), nullable=True),
    sa.Column('preferred_end_date', sa.Date(), nullable=True),
    sa.Column('expected_group_size', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('preferences_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=False),
    sa.Column('cover_image_url', sa.String(length=1500), nullable=True),
    sa.Column('cover_image_source', sa.String(length=30), nullable=True),
    sa.Column('cover_attribution_name', sa.String(length=200), nullable=True),
    sa.Column('cover_attribution_url', sa.String(length=1000), nullable=True),
    sa.Column('cover_source_url', sa.String(length=1000), nullable=True),
    sa.Column('cover_image_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_link',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trip_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('plan',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trip_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('estimated_total_per_person', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('needs_refresh', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_membership',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trip_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('guest_display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('join_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('one_membership_per_user_per_trip', 'trip_membership', ['trip_id', 'user_id'], unique=True, postgresql_where='user_id IS NOT NULL')
    op.create_table('member_constraint',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trip_membership_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_membership_id'], ['trip_membership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_item',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('start_hour', sa.Float(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('local_title', sa.String(length=300), nullable=True),
    sa.Column('place', sa.String(length=500), nullable=False),
    sa.Column('price_per_person', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('dietary_tags', sa.JSON(), nullable=False),
    sa.Column('is_meal', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('settledness', sa.String(length=20), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_by_round_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preference',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trip_membership_id', sa.String(length=32), nullable=False),
    sa.Column('preferred_start_date', sa.Date(), nullable=True),
    sa.Column('preferred_end_date', sa.Date(), nullable=True),
    sa.Column('available_start_date', sa.Date(), nullable=True),
    sa.Column('available_end_date', sa.Date(), nullable=True),
    sa.Column('ideal_budget', sa.Float(), nullable=True),
    sa.Column('maximum_budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('budget_visibility', sa.String(length=20), nullable=False),
    sa.Column('travel_style', sa.String(length=40), nullable=True),
    sa.Column('top_interests', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_membership_id'], ['trip_membership.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_membership_id')
    )
    op.create_table('change_proposal',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_item_id', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=False),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_by_membership_id', sa.String(length=32), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], ),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['trip_membership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('one_pending_proposal_per_item', 'change_proposal', ['plan_item_id'], unique=True, postgresql_where="status = 'waiting_affected_members'")
    op.create_table('decision_round',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_item_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('winning_option_id', sa.String(length=40), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('one_open_round_per_item', 'decision_round', ['plan_item_id'], unique=True, postgresql_where="status = 'open'")
    op.create_table('member_constraint_private',
    sa.Column('constraint_id', sa.String(length=32), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['constraint_id'], ['member_constraint.id'], ),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_table('plan_change',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('plan_item_id', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('patch', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_membership_id', sa.String(length=32), nullable=True),
    sa.Column('source_round_id', sa.String(length=32), nullable=True),
    sa.Column('source_proposal_id', sa.String(length=32), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_item_comment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_item_id', sa.String(length=32), nullable=False),
    sa.Column('trip_membership_id', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], ),
    sa.ForeignKeyConstraint(['trip_membership_id'], ['trip_membership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_notice',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trip_id', sa.String(length=32), nullable=False),
    sa.Column('plan_item_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('recipient_membership_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('can_object', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_decision',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('proposal_id', sa.String(length=32), nullable=False),
    sa.Column('trip_membership_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['change_proposal.id'], ),
    sa.ForeignKeyConstraint(['trip_membership_id'], ['trip_membership.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'trip_membership_id')
    )
    op.create_table('vote',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('round_id', sa.String(length=32), nullable=False),
    sa.Column('trip_membership_id', sa.String(length=32), nullable=False),
    sa.Column('option_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['decision_round.id'], ),
    sa.ForeignKeyConstraint(['trip_membership_id'], ['trip_membership.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'trip_membership_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('proposal_decision')
    op.drop_table('update_notice')
    op.drop_table('plan_item_comment')
    op.drop_table('plan_change')
    op.drop_table('member_constraint_private')
    op.drop_index('one_open_round_per_item', table_name='decision_round', postgresql_where="status = 'open'")
    op.drop_table('decision_round')
    op.drop_index('one_pending_proposal_per_item', table_name='change_proposal', postgresql_where="status = 'waiting_affected_members'")
    op.drop_table('change_proposal')
    op.drop_table('preference')
    op.drop_table('plan_item')
    op.drop_table('member_constraint')
    op.drop_index('one_membership_per_user_per_trip', table_name='trip_membership', postgresql_where='user_id IS NOT NULL')
    op.drop_table('trip_membership')
    op.drop_table('plan')
    op.drop_table('invite_link')
    op.drop_table('trip')
    op.drop_table('auth_session')
    op.drop_table('user_account')
    op.drop_index('ix_place_city_country', table_name='place')
    op.drop_table('place')
    # ### end Alembic commands ###
